### ISSUE TITLE
doesn't work with pip install

### ISSUE THREAD

**Issue by vikaslalwani** [scottchiefbaker/dool#78]
##### SUMMARY
I tried a `pip install dool` in a `python 3.12.6` virtual env and no other command works except `dool --help`

##### ISSUE TYPE

 - Bug Report

##### DOOL VERSION

`1.3.2`

##### OS / ENVIRONMENT

`macOs sonoma 14.6.1` - `Intel 2019`

##### ACTUAL RESULTS

`dool --vmstat`

```

Traceback (most recent call last):
  File "/myhome/venv/lib/python3.12/site-packages/dool.py", line 2721, in main
    exec('global plug; plug = %s()' % pluginfile)
  File "<string>", line 1, in <module>
  File "/myhome/venv/lib/python3.12/site-packages/dool.py", line 1335, in __init__
    self.open('/proc/stat')
  File "/myhome/venv/lib/python3.12/site-packages/dool.py", line 545, in open
    raise Exception('Cannot open file %s' % filename)
Exception: Cannot open file /proc/stat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/myhome/venv/bin/dool", line 8, in <module>
    sys.exit(__main())
             ^^^^^^^^
  File "/myhome/venv/lib/python3.12/site-packages/dool.py", line 3045, in __main
    main()
  File "/myhome/venv/lib/python3.12/site-packages/dool.py", line 2726, in main
    if mod == mods[-1]:
       ^^^
NameError: name 'mod' is not defined

```

**Comment by vikaslalwani** [comment]
Update
---

Turns out that when I do a regular install on mac, it still doesn't work. 

After executing `install.py`, Instead of creating `dool` binary in my `/usr/local/bin` it creates it in `/Users/myhome/bin/dool` 

I tried moving the binary to `mv /Users/myhome/bin/dool /usr/local/bin/` and executing it, it ends up in same error as encountered via `pip install` 

```
dool --vmstat
Traceback (most recent call last):
  File "/usr/local/bin/dool", line 2721, in main
    exec('global plug; plug = %s()' % pluginfile)
  File "<string>", line 1, in <module>
  File "/usr/local/bin/dool", line 1335, in __init__
    self.open('/proc/stat')
  File "/usr/local/bin/dool", line 545, in open
    raise Exception('Cannot open file %s' % filename)
Exception: Cannot open file /proc/stat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dool", line 3057, in <module>
    __main()
  File "/usr/local/bin/dool", line 3045, in __main
    main()
  File "/usr/local/bin/dool", line 2726, in main
    if mod == mods[-1]:
       ^^^
NameError: name 'mod' is not defined
```

**Comment by scottchiefbaker** [comment]
@benfishbus can you take a look at pip?

**Comment by scottchiefbaker** [comment]
@vikaslalwani dool is a Linux system monitoring tool, and will not work on MacOS. The error you're receiving is dool saying that it cannot read from `/proc/stat` because it doesn't exist on MacOS.
