### ISSUE TITLE
Specifying disk devices with deep symlink path breaks -r (-d is fine)

### ISSUE THREAD

**Issue by Korkman** [scottchiefbaker/dool#79]
##### SUMMARY
Specifying disk devices with deep symlink path breaks `-r` (`-d` is fine)

##### ISSUE TYPE
 - Bug Report

##### DOOL VERSION
1.3.2

##### OS / ENVIRONMENT
Ubuntu Noble, MX Linux, Debian

##### STEPS TO REPRODUCE
```bash
$ dool -r -D "/dev/disk/by-path/pci-0000:00:14.0-usb-0:6:1.0-scsi-0:0:0:0"
```

##### EXPECTED RESULTS
I/O stats

##### ACTUAL RESULTS
```
Traceback (most recent call last):
  File "/usr/local/bin/dool", line 2723, in main
    plug.prepare()
  File "/usr/local/bin/dool", line 506, in prepare
    raise Exception('No counter objects to monitor')
Exception: No counter objects to monitor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dool", line 3057, in <module>
    __main()
  File "/usr/local/bin/dool", line 3045, in __main
    main()
  File "/usr/local/bin/dool", line 2726, in main
    if mod == mods[-1]:
       ^^^
NameError: name 'mod' is not defined
```

**Comment by scottchiefbaker** [comment]
I think I figured this out in commit 8de8e35. Works on my local machine if I use:

```
dool --io -D /dev/disk/by-uuid/883e5732-db9f-41d4-8df2-809672f43b0e
```

Can you test and let me know?

**Comment by Korkman** [comment]
Fix confirmed!
